### ISSUE TITLE
How to get secret key

### ISSUE THREAD

**Issue by maxpd1** [iobroker-community-adapters/ioBroker.synology#84]
I can't follow the instructions here as I don't see the button "You can also enter your key manually" 

https://github.com/iobroker-community-adapters/ioBroker.synology/blob/master/docs/en/template.md

I use DSM 7.

**Comment by bjornand1** [comment]
I have the same issue, I can only generate the temporary 6-character code.

**Comment by steffensammet** [comment]
Did anyone manage to get this adapter working with DSM7 ?

**Comment by Apollon77** [comment]
Is this still an issue with the 2.0.1 from GitHub here?

**Comment by steffensammet** [comment]
This is very difficult to answer as we could reach this step. The provided manual for 2FA does not apply to DSM7.

**Comment by Apollon77** [comment]
> as we could reach this step.

What yopu mean?

Can anyone provide a manual for DSM7? Because I assume some already use the adapter with it ...

**Comment by steffensammet** [comment]
Hello all,

I could solve it. Perhaps it is now solved due to new DSM7 version. I am actually running DSM 7.0.1-42218 Update 3.

Here is the path to make it work:
Click on "user  options" => "personal" => "2FA" => Verification Code (OTP) => Reset devices => "Can't scan it?" and here you get the secret key - copy and paste this to iobroker, go back, scan the code with your mobile and validate it. 

Enjoy :-)

Br,
Steffen

**Comment by bjornand1** [comment]
Sounds promising, but it still does not work for me. I get the plugin to run, but the DSM is shown as turned off, despite being on, and the temperature just reads 0 degrees.

**Comment by Apollon77** [comment]
@bjornand1  But this sounds like an other issue or? What does the log say (but in a new issue of forum please)

**Comment by Tobsen1599** [comment]
Awesome, that worked for me. Thanks

**Comment by Tobsen1599** [comment]
> Hello all,
> 
> I could solve it. Perhaps it is now solved due to new DSM7 version. I am actually running DSM 7.0.1-42218 Update 3.
> 
> Here is the path to make it work: Click on "user options" => "personal" => "2FA" => Verification Code (OTP) => Reset devices => "Can't scan it?" and here you get the secret key - copy and paste this to iobroker, go back, scan the code with your mobile and validate it.
> 
> Enjoy :-)
> 
> Br, Steffen

Great, that worked for me. Thanks

**Comment by maxpd1** [comment]
@steffensammet also with your detailed manual, I don't get it run. I followed every step successfully, but the instance keeps being disconnected.
